---
language: python
python: "2.7"
services:
  - docker

# Use the new container infrastructure
sudo: false

install:
  pip install molecule docker

script:
  - molecule --version
  - ansible --version
  - molecule test


# Install ansible
addons:
  apt:
    packages:
    - python-pip

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  